Test groups.go
maddevsio/mad-internship-bot pull request #49
Opened 2019-07-17 12:07 UTC by sula7

Tested groups.go in file groups_test.go
Coverage 53.7%

2019-07-17 12:09 UTC, anatoliyfedorenko requested changes

2019-07-17 12:09 UTC, anatoliyfedorenko commented on storage/groups_test.go
> +		Username:         "SulaFPV",
Сделай значения более нейтральными. Не `SulaFPV` а например `Foo` и т.д.

2019-07-17 14:28 UTC, anatoliyfedorenko commented on storage/groups_test.go
> +	require.NoError(t, err)
откуда ты знаешь что группы удалились? Добавь тест на это.

2019-07-18 07:45 UTC, sula7 commented on storage/groups_test.go
> +	require.NoError(t, err)
Исправлено

2019-07-18 07:45 UTC, sula7 commented on storage/groups_test.go
> +		Username:         "SulaFPV",
Исправлено

2019-07-18 09:22 UTC, anatoliyfedorenko approved these changes

2019-07-18 09:23 UTC, merged