Add tests to functions in file standups.go
maddevsio/mad-internship-bot pull request #50
Opened 2019-07-17 13:45 UTC by BekbolotGM

Test coverage 61%
#46

2019-07-17 14:27 UTC, anatoliyfedorenko requested changes
Нужно дополнить тесты, тогда приму

2019-07-17 14:27 UTC, anatoliyfedorenko commented on storage/standups_test.go
> +	standup, err = mysql.SelectStandup(standup.ID)
а где проверка на то, что это реально тот стендап?

2019-07-17 14:27 UTC, anatoliyfedorenko commented on storage/standups_test.go
> +	require.NoError(t, err)
И здесь такой проверки нет. Ты проверяешь что функция просто отработала а надо чтобы она отработала правильно.

2019-07-17 14:27 UTC, anatoliyfedorenko commented on storage/standups_test.go
> +	_, err = mysql.LastStandupFor(standup.Username, standup.ChatID)
а как ты докажешь что это именно последний стендап пользователя а не предпоследний? или не первый?

2019-07-17 14:27 UTC, anatoliyfedorenko commented on storage/standups_test.go
> +	require.NoError(t, err)
Здесь тоже можно было бы проверить что стендапа в базе больше нет. Пиши тесты значимые и логичные, а не просто чтобы были.

2019-07-18 06:10 UTC, anatoliyfedorenko commented on storage/standups_test.go
> +	require.Equal(t, standup.ID, standup.ID)
ты сравниваешь одно и то же. Проверка всегда пройдет, даже если в действительности ID разные. и сравнивай не ID а хотябы Channel ID , чтобы можно было захардкодить. иначе будет путаница

2019-07-18 08:12 UTC, BekbolotGM commented on storage/standups_test.go
> +	require.Equal(t, standup.ID, standup.ID)
Изменил

2019-07-18 09:21 UTC, anatoliyfedorenko approved these changes

2019-07-18 09:21 UTC, merged