CheckNotificationThread
maddevsio/mad-internship-bot pull request #69
Opened 2019-08-30 08:23 UTC by BekbolotGM

Функция CheckNotificationThread() уведомляет пользователся не написавшего стендап 3 раза каждые 30 мин.

2019-08-30 09:26 UTC, anatoliyfedorenko commented on bot/notifications.go
> +const maxReminder = 3
Перемести константы в конфиг хотябы. в идеале это вообще должны быть настройки группы. так как каждый сам волен указывать сколько раз напоминать, через сколько минут и т.д.

2019-09-02 11:35 UTC, anatoliyfedorenko commented on bot/notifications.go
> +				return
должно быть continue

2019-09-02 11:36 UTC, anatoliyfedorenko commented on bot/notifications.go
> +			log.Error("Error on executing CheckNotificationThread! ", err)
лог потом не найдём. поправить

2019-09-02 11:36 UTC, anatoliyfedorenko requested changes

2019-09-02 11:36 UTC, anatoliyfedorenko commented on bot/notifications.go
> +				log.Error("Error on executing DeleteNotificationsThread! ", err)
укажи хоть какой это трэд, чтобы понять ,что пошло не так.

2019-09-02 11:59 UTC, BekbolotGM commented on bot/notifications.go
> +				log.Error("Error on executing DeleteNotificationsThread! ", err)
То есть ID треда?

2019-09-03 04:35 UTC, anatoliyfedorenko requested changes

2019-09-03 04:35 UTC, anatoliyfedorenko commented on bot/notifications.go
> +			log.Error("Error on executing CreateNotificationThread ", err)
тоже надо вставить что-нибдуь чтобы понять, с какими именно параметрами функция упала.

2019-09-03 04:35 UTC, anatoliyfedorenko commented on bot/notifications.go
> +			log.Error("Error on executing ListNotificationsThread! ", err)
тоже надо вставить что-нибудь чтобы понять, с какими именно параметрами функция упала.

2019-09-03 04:35 UTC, anatoliyfedorenko commented on bot/notifications.go
> +		log.Error("Error on executing ListNotificationThread! ", err)
вставить group.ChatID в логгер. Везде оставляй конкретные данные, чтобы понять больше. когда будешь дебажить, поблагодаришь

2019-09-03 04:35 UTC, anatoliyfedorenko commented on bot/notifications.go
> +		if t.Hour() == thread.NotificationTime.In(loc).Hour() || t.Minute() == thread.NotificationTime.In(loc).Minute() {
у тебя очень большая матрёшка из if условий. Можно было сделать так, что если время не равно времени треда, то просто пропускать, а в других случаях делать код, который ниже. Чем больше у тебя вложенных условий, тем тяжелее код читать.

2019-09-03 04:35 UTC, anatoliyfedorenko commented on bot/notifications.go
> +					Other: "Attention, @{{.Intern}}! you still haven't written a standup! Write a standup!",
Замени здесь тоже слово intern. по всему коду нужно от этого избавиться. можно просто standuper , так как бот больше не для стажёров

2019-09-03 04:35 UTC, anatoliyfedorenko commented on bot/notifications.go
> +				log.Error("Error sending message, CheckNotificationThread! ", err)
Тоже нужны доп параметры! Не поймёшь же в какую группу отправлял, запутаешься в логах.

2019-09-03 04:35 UTC, anatoliyfedorenko commented on config/config.go
> +	NotificationTime int
А тэги для MaxReminders и NotificationTime ты решил не прописывать? пример то, что выше, тебя вообще никак не насторожил да? Там ведь и default есть (значение по умолчанию) и envconfig ( ты ведь вообще не разобрался что это и у меня тоже не уточнил, нужно ли что-либо с этим делать. не почитал доку.

2019-09-03 04:35 UTC, anatoliyfedorenko commented on config/config.go
> +	var c = BotConfig{
Убери эту порнографию и лучше в тэги вставь default значения...

2019-09-03 07:03 UTC, anatoliyfedorenko commented on bot/notifications.go
> +		if t.Hour() != thread.NotificationTime.In(loc).Hour() || t.Minute() != thread.NotificationTime.In(loc).Minute() {
исправить. не надо так делать ))

2019-09-03 11:33 UTC, anatoliyfedorenko commented on config/config.go
> +	MaxReminder      int    `default:"3"`
добавь envconfig и как должно называться в .env файле этот параметр.

2019-09-03 11:47 UTC, merged